[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
keywords = ["zstd", "zstandard", "compression"]
categories = ["compression", "api-bindings"]
license = "MIT"
name = "zstd"
repository = "https://github.com/gyscos/zstd-rs"
version ="0.4.21+zstd.1.3.7"
exclude = ["assets/**"]
readme = "Readme.md"

[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
zstd-safe = { path="zstd-safe", version = "1.4.5", default-features = false }
tokio-io = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
clap = "2.6.0"
partial-io = "0.3"
quickcheck = "0.6"
humansize = "1.0"
walkdir = "2.2.5"

[features]
default = ["legacy"]
legacy = ["zstd-safe/legacy"]
bindgen = ["zstd-safe/bindgen"]
tokio = ["tokio-io", "futures", "partial-io/quickcheck", "partial-io/tokio"]
wasm = ["zstd-safe/std"] # To compile on wasm we need to avoid using libc
