[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
keywords = ["zstd", "zstandard", "compression"]
categories = ["compression", "api-bindings"]
license = "MIT"
name = "zstd"
repository = "https://github.com/gyscos/zstd-rs"
version = "0.4.6"
exclude = ["assets"]

[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
libc = "0.2"
zstd-sys = { version = "1.1.5-a", default-features = false }

[dev-dependencies]
clap = "2.6.0"

[features]
default = ["legacy"]
legacy = ["zstd-sys/legacy"]
bindgen = ["zstd-sys/bindgen"]
