[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
keywords = ["zstd", "zstandard", "compression"]
categories = ["compression", "api-bindings"]
license = "MIT"
name = "zstd"
repository = "https://github.com/gyscos/zstd-rs"
version = "0.4.15+zstd.1.3.2"
exclude = ["assets"]
readme = "Readme.md"

[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
libc = "0.2"
zstd-safe = { path="zstd-safe", version = "1.4", default-features = false }
tokio-io = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
clap = "2.6.0"
partial-io = "^0.2.1"
quickcheck = "0.4"

[features]
default = ["legacy"]
legacy = ["zstd-safe/legacy"]
bindgen = ["zstd-safe/bindgen"]
tokio = ["tokio-io", "futures", "partial-io/quickcheck", "partial-io/tokio"]
